appname="局域网快传"
appver="1.0"
appcode="1"
appsdk="21"
path_pattern=""
packagename="com.dingyi.demo"
theme="Theme_DeviceDefault_Light"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
