name: Make Latest Folder On EmulatorJS CDN
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    if: github.repository == 'EmulatorJS/EmulatorJS'
    runs-on: emulatorjs-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Script
        run: |
          cd /public
          ./.latest.sh
