name: Make Stable Folder On EmulatorJS CDN
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    if: github.repository == 'EmulatorJS/EmulatorJS'
    runs-on: emulatorjs-server
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Script
        run: |
          cd /public
          ./.stable.sh
